### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by mrkaban** [TechLearnersInc/Free-Hash-Checker#1]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D1%8C/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/free-hash-checker.html).

The project is interesting, so please don't abandon it!

**Comment by skinan** [comment]
Thanks for the appreciation and support. Your support is a valuable asset for us.
